version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: calvio-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  algorithm:
    build: ./algorithm-microservice
    container_name: calvio-algorithm
    ports:
      - "8000:8000"
    volumes:
      - ./algorithm-microservice:/app
